#!/bin/bash
mkdir -p ~/.backup/dotfiles

for dotfile in .bashrc .gitconfig .tmux.conf .vimrc
do
	if test -f ~/$dotfile
	then
		mv -n ~/$dotfile ~/.backup/dotfiles
	fi
	ln -s ~/dotfiles/$dotfile ~/$dotfile 2> /dev/null
done
